spring.application.name=classmanager

# Show the actual SQL Hibernate generates ? great for learning/debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable H2's browser-based database console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Tell Hibernate to auto-create tables based on our @Entity classes
# (update = create tables if missing, but don't wipe existing data on restart)
spring.jpa.hibernate.ddl-auto=update